name: Code Quality Checks

on:
  push:
    branches: ["main"]
  pull_request:

# Kill existing jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-autopep8-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-autopep8
      - run: |
          python -m pip install --upgrade pip
          pip install autopep8 isort
      - run: autopep8 --diff --exit-code $(git ls-files '*.py')
      - run: isort --diff --check $(git ls-files '*.py')

  # run-unittest:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         cache: "pip"
  #     - run: python -c "import sys; print(sys.version)"
  #     - run: |
  #         python -m pip install --upgrade pip
  #         pip install --editable .
  #     - run: python -m unittest
